import Head from "next/head";

export default function Meta({ title }) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/bzcmp-ico.png" />
    </Head>
  );
}
